server:
  port: 7090
spring:
  application:
    name: spring-cloud-user
  security:
    user:
      name: admin
      password: admin123
logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
