server:
  port: 9090
spring:
  application:
    name: spring-cloud-user-ribbon
logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
